// Truthy value & Falsy Value

// 1)
const userEmail = "d@ai.com"

// if (userEmail) {
//     console.log("Got the user email");
// } else {
//     console.log("Don't have user email");
// }

// Here we didn't compare for thee condition in if statement, despite of that output will be generated by assuming that passed string is true value. This is known as truthy value


// Falsy Values:
    // false, 0, -0, BigInt 0n, "", null, undefined, NaN

// Truthy Values:
    // "0", "false", " ", [], {}, function(){} 



// 2)
const scores = []

// if (scores.length === 0) {
//     console.log("Array is Empty");
// }



// 3)
const emptyObj = {}

// if (Object.keys(emptyObj).length === 0) {
//     console.log("Object is Empty");
// } 


// Nullish Coalescing Opeartor (??) => null, undefined

let val1;
// val1 = 5 ?? 10                    // 5
// val1 = null ?? 10                // 10
// val1 = undefined ?? 52          // 52
// val1 = null ?? undefined       // undefined
val1 = null ?? 10 ?? 30          // 10
// console.log(val1);


// Terniary Operator

// condition ? true : false 

const iceTeaPrice = 100
iceTeaPrice <= 80 ? console.log("Less than 80") : console.log("More than 80");